### ISSUE TITLE
The favicon should be -> https://mumuki.io/logo-alt.png

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-styles#18]
https://github.com/mumuki/mumuki-styles/blob/fd79ae376f7e7327ff196ed7105bf55e78ffeeea/src/javascripts/_web-browser.js#L5

**Comment by fedescarpa** [comment]
Fu@#$%^ typo

fixed in https://github.com/mumuki/mumuki-styles/commit/4a1cc22438b4090616317386964aa35e739196c1#diff-316fd3fdc6ef8d450c3d15ea0339dd5dR6
