### ISSUE TITLE
DER del corolario descompaginado

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-styles#19]
Cuando el editor está "maximizado", no hay problemas con el DER en el editor, pero al dividirlo en columnas, el DER del ejercicio queda así...
![ejercicio](https://user-images.githubusercontent.com/7552150/34488248-7e5287ae-efb6-11e7-8416-e89f394ca52a.jpg)

...y el del corolario se desarma:
![corolario](https://user-images.githubusercontent.com/7552150/34488247-7e32b672-efb6-11e7-9adf-e04d001bd1af.jpg)

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-styles/commit/d10079e5b4b37bc6bc930b45d3a13d9fbb8491e8
