### ISSUE TITLE
Customizar tabla para ejercicio de "muchos a muchos"

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-styles#25]
Estaría bueno solo para el [ejercicio 8 de la guía 3](https://staging.mumuki.io/exercises/4269-bases-de-datos-relaciones-claves-todos-con-todos) que en el corolario se muestre una tabla "especial" con mezcla de DER para no tener que mostrar ambos, y que tenga distintos colores para distinguir que cada combinación es única. 
Se puede hablar con Moni para elegir algún modelo copado y no muy agobiante. 

![image](https://user-images.githubusercontent.com/7552150/35011307-66d6c8ae-fae4-11e7-8cfc-26f0b968a994.png)

**Comment by cucusita** [comment]
chi, juntemono'  y lo armamo'

**Comment by fedescarpa** [comment]
Al final no fue necesario hacer una UI genérica. Ya está hecha la imagen para este caso específico. Cierro el issue
