### ISSUE TITLE
Margin in "copiar" button in code snippet.

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mumuki-styles#28]
Button overlaps with text in long sentences.

**Comment by luchotc** [comment]
Although this particular issue was fixed, i'm reopening it because when the first line doesn't take all width, the margin doesn't look good at all: 

![image](https://user-images.githubusercontent.com/11860076/54154032-c0278080-441f-11e9-91ab-9c39d4c92074.png)

**Comment by luchotc** [comment]
Also, this style is applied even when no copy button is present.

**Comment by flbulgarelli** [comment]
Closed by https://github.com/mumuki/mumuki-styles/pull/42
