### ISSUE TITLE
ERD component breaks when the svg are not present in the screen

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-styles#35]
In a discussion, the description isn't visible, so the SVG is not present and the components fails.
We shouldn't try to draw the lines if the SVG's aren't present. 
In labo, we'll need to trigger an event on tab change, to generate the re-render.

To reproduce this issue, go to a discussion for a SQL exercise.

**Comment by Javi** [comment]
Is there any available link to a discussion I can check out to reproduce?

**Comment by flbulgarelli** [comment]
@luchotc ?

**Comment by luchotc** [comment]
Yep, it could be this one: https://mumuki.io/sanluis/exercises/5130-modelos-de-examen-simulacro-de-examen-1-consulta-sql/discussions/1238, but it happens in any discussion involving a sqlite exercise!

**Comment by Javi** [comment]
My account doesn't have access to it, can you add me please?

**Comment by flbulgarelli** [comment]
@rgonzalezt
