### ISSUE TITLE
Dist folder is not updated

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-styles#41]
After generating local dist for testing, i noticed that contents in dist folder are not updated.
So, we should update it or add it to .gitignore

**Comment by fedescarpa** [comment]
Dist debería actualizarse solo ante una nueva version, de hecho debería estar ignorada la folder solo generarla para el deploy

**Comment by flbulgarelli** [comment]
Entonces la solución es ignorarla, no?

**Comment by luchotc** [comment]
Si pero hay que asegurarnos que en el deploy se siga incluyendo la misma

**Comment by felipecalvo** [comment]
The solution at https://github.com/mumuki/mumuki-styles/commit/b8067aa93efcfda19babe546539099312ad4b31b is not ideal but it's definitely better than what we used to have at the time.
