### ISSUE TITLE
Improve dependencies managment

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-styles#5]
Currently, in order to mumukit-assets to work, we need the following: 

* bootstrap
* bootstrap-flatly
* font-awesome
* https://github.com/mumuki/dev-awesome

This repo does nothing about it, so it is hard to include them and error prone. It would be nice that adding mumukit-assets automatically includes them, so that we need to just include a sass dependency. 

This issue is important because we need to

* include those styles in mumukit-office and the documentation site,  
* replace laboratory custom css with this repository
* use it in bibliotheca and classroom consistently

**Comment by flbulgarelli** [comment]
@aguspina @fedescarpa @dggluz @rodri042 

I would like to have your feedback.

**Comment by fedescarpa** [comment]
`%s/mumuki-assets/mumuki-styles/g`

You're right, we should add those dependencies

According to the bower documentation
> Bower is optimized for the front-end. If multiple packages depend on a package - jQuery for example - Bower will download jQuery just once. This is known as a **flat dependency graph** and it helps reduce page load.

**Comment by flbulgarelli** [comment]
:smile:
